### ISSUE TITLE
question about text

### ISSUE THREAD

**Issue by harborsarah** [Adonis-galaxy/WorDepth#1]
Dear authors,

I have a question regarding the generated text. How did you generate the text for each image? Are they first generated, saved locally, and directly taken during training the WorDepth? Thanks a lot for your reply.

**Comment by Adonis-galaxy** [comment]
Hi, thank you for your interest! Text is generated using ExpensionNet v2 (https://github.com/jchenghu/ExpansionNet_v2), extracted text features using CLIP text encoder (ResNet-50), then saved text features locally, and directly taken during training and inference. We will release this part of code later~

**Comment by Adonis-galaxy** [comment]
Hi, all text and pre-extracted text features have been uploaded to this repo. WorDepth should be able to train now.
