### ISSUE TITLE
test in the wild

### ISSUE THREAD

**Issue by leilai125** [Adonis-galaxy/WorDepth#4]
Hi, do we have the code for testing the model in the wild? Thanks!

**Comment by Adonis-galaxy** [comment]
Hi! For testing the model in the wild, you could first label (or prompt) text captions for each image, extract the text feature of images using CLIP, then use our evaluation code~

**Comment by leilai125** [comment]
Thanks! I didn't find any evaluation code. Should we revise based on the train code?

**Comment by Adonis-galaxy** [comment]
Hi. The evaluation code is part of the training code. Please see the section "Eval NYU-Depth-v2 or KITTI" inside the README~
